#springboot application config file 
server:
  port: 8080
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations:
     - classpath:mapping/*.xml
  type-aliases-package: com.majq.seckill.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
spring:
  datasource:
    druid:
      filter: stat,wall,log4j
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1
  resources:
    static-locations:
      - classpath:/static/img/
      - classpath:/static/css/
      - classpath:/static/js/
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

        