#springboot application config file 
server:
  port: 8080
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations:
     - classpath:mapping/*.xml
  type-aliases-package: com.majq.seckill.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
spring:
  datasource:
    druid:
      filter: stat
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1
  mvc:
    view:
      suffix: .html
logging:
  config: classpath:logback-spring.xml

        